'use client';

import React, { useEffect, useState, useCallback } from 'react';
import { useRouter } from 'next/navigation';
import {
  AlertTriangle,
  Filter,
  RefreshCw,
  Activity,
  Calendar,
  Layers,
  Brain,
  Loader2,
} from 'lucide-react';
import type {
  EventMetrics,
  SecurityEvent,
  SecurityEventSeverity,
  SecurityEventStatus,
  SecurityEventType,
} from '@/types';
import { getEventMetrics, getSecurityEvents } from '@/services/securityEvents';
import { createIncidentReport } from '@/services/incidents';
import EventTable from '@/components/security/EventTable';
import MetricCard from '@/components/dashboard/MetricCard';

export default function SecurityEventsPage() {
  const router = useRouter();
  const [events, setEvents] = useState<SecurityEvent[]>([]);
  const [metrics, setMetrics] = useState<EventMetrics>({
    total_events: 0,
    open_events: 0,
    high_severity_events: 0,
    medium_severity_events: 0,
    low_severity_events: 0,
    events_today: 0,
    by_type: {},
  });
  const [isLoading, setIsLoading] = useState(true);
  const [selectedEventIds] = useState<string[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);

  // Filters
  const [selectedType, setSelectedType] = useState<string>('all');
  const [selectedSeverity, setSelectedSeverity] = useState<string>('all');
  const [selectedStatus, setSelectedStatus] = useState<string>('all');

  const loadData = useCallback(async () => {
    setIsLoading(true);
    try {
      const [eventsData, metricsData] = await Promise.all([
        getSecurityEvents({
          event_type: selectedType !== 'all' ? (selectedType as SecurityEventType) : undefined,
          severity: selectedSeverity !== 'all' ? (selectedSeverity as SecurityEventSeverity) : undefined,
          status: selectedStatus !== 'all' ? (selectedStatus as SecurityEventStatus) : undefined,
          limit: 100,
        }),
        getEventMetrics(),
      ]);
      setEvents(eventsData);
      setMetrics(metricsData);
    } catch {
      setEvents([]);
    } finally {
      setIsLoading(false);
    }
  }, [selectedType, selectedSeverity, selectedStatus]);

  useEffect(() => {
    loadData();
  }, [loadData]);

  const handleGenerateReport = async () => {
    // Use selected events if any, otherwise fall back to first 20 visible
    const ids =
      selectedEventIds.length > 0
        ? selectedEventIds
        : events.slice(0, 20).map((e) => e.id);

    if (ids.length === 0) {
      alert('No events available to generate a report from.');
      return;
    }
    if (ids.length > 50) {
      alert('Please select up to 50 events for a single report.');
      return;
    }

    setIsGenerating(true);
    try {
      const report = await createIncidentReport({ event_ids: ids });
      router.push(`/dashboard/incidents/${report.id}`);
    } catch (err: unknown) {
      const errorMsg =
        (err as { response?: { data?: { detail?: string } } })?.response?.data?.detail ??
        'Failed to generate AI incident report. Please try again.';
      alert(errorMsg);
    } finally {
      setIsGenerating(false);
    }
  };


  const kpis = [
    {
      label: 'Open Events',
      value: metrics.open_events,
      subtext: 'Requires review or acknowledgment',
      icon: AlertTriangle,
      iconColor: metrics.open_events > 0 ? '#ef4444' : '#22c55e',
      iconBg: metrics.open_events > 0 ? 'rgba(239,68,68,0.1)' : 'rgba(34,197,94,0.1)',
    },
    {
      label: 'High Severity',
      value: metrics.high_severity_events,
      subtext: 'High operational priority violations',
      icon: Activity,
      iconColor: '#f97316',
      iconBg: 'rgba(249,115,22,0.1)',
    },
    {
      label: 'Medium Severity',
      value: metrics.medium_severity_events,
      subtext: 'Standard temporal rule events',
      icon: Layers,
      iconColor: '#f59e0b',
      iconBg: 'rgba(245,158,11,0.1)',
    },
    {
      label: 'Events Today',
      value: metrics.events_today,
      subtext: 'Triggered in the last 24h window',
      icon: Calendar,
      iconColor: '#3b7dd8',
      iconBg: 'rgba(59,125,216,0.1)',
    },
  ];

  return (
    <div className="max-w-6xl mx-auto space-y-6">
      {/* Header */}
      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-xl font-semibold text-[#e8edf5]">Security Events &amp; Incident Intelligence</h1>
          <p className="text-sm text-[#8b96a8] mt-1">
            Algorithmic event triggers generated by SentinelAI vision and temporal tracking rules.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={handleGenerateReport}
            disabled={isGenerating || events.length === 0}
            className="px-3 py-1.5 rounded-lg bg-violet-600/20 border border-violet-500/30 text-xs text-violet-300 hover:bg-violet-600/30 flex items-center gap-1.5 transition-colors disabled:opacity-50"
          >
            {isGenerating ? (
              <Loader2 className="w-3.5 h-3.5 animate-spin" />
            ) : (
              <Brain className="w-3.5 h-3.5" />
            )}
            {isGenerating ? 'Generating…' : 'Generate AI Report'}
          </button>
          <button
            type="button"
            onClick={loadData}
            disabled={isLoading}
            className="px-3 py-1.5 rounded-lg bg-[#111620] border border-[#1e2736] text-xs text-[#8b96a8] hover:text-[#e8edf5] flex items-center gap-1.5 transition-colors disabled:opacity-50"
          >
            <RefreshCw className={`w-3.5 h-3.5 ${isLoading ? 'animate-spin' : ''}`} />
            Refresh
          </button>
        </div>
      </div>

      {/* KPI Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {kpis.map((kpi) => (
          <MetricCard key={kpi.label} {...kpi} />
        ))}
      </div>

      {/* Filters Bar */}
      <div className="bg-[#111620] border border-[#1e2736] rounded-xl p-4 flex flex-wrap items-center justify-between gap-3 text-xs">
        <div className="flex items-center gap-2 text-[#8b96a8]">
          <Filter className="w-4 h-4 text-[#3b7dd8]" />
          <span className="font-medium text-[#e8edf5]">Event Filters:</span>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          {/* Status Filter */}
          <select
            value={selectedStatus}
            onChange={(e) => setSelectedStatus(e.target.value)}
            className="px-2.5 py-1.5 rounded-lg bg-[#0e131d] border border-[#1e2736] text-[#e8edf5] focus:outline-none focus:border-[#3b7dd8]"
          >
            <option value="all">All Statuses</option>
            <option value="OPEN">Open</option>
            <option value="ACKNOWLEDGED">Acknowledged</option>
            <option value="RESOLVED">Resolved</option>
            <option value="DISMISSED">Dismissed</option>
          </select>

          {/* Severity Filter */}
          <select
            value={selectedSeverity}
            onChange={(e) => setSelectedSeverity(e.target.value)}
            className="px-2.5 py-1.5 rounded-lg bg-[#0e131d] border border-[#1e2736] text-[#e8edf5] focus:outline-none focus:border-[#3b7dd8]"
          >
            <option value="all">All Severities</option>
            <option value="CRITICAL">Critical</option>
            <option value="HIGH">High</option>
            <option value="MEDIUM">Medium</option>
            <option value="LOW">Low</option>
          </select>

          {/* Event Type Filter */}
          <select
            value={selectedType}
            onChange={(e) => setSelectedType(e.target.value)}
            className="px-2.5 py-1.5 rounded-lg bg-[#0e131d] border border-[#1e2736] text-[#e8edf5] focus:outline-none focus:border-[#3b7dd8]"
          >
            <option value="all">All Event Types</option>
            <option value="INTRUSION">Restricted Zone Intrusion</option>
            <option value="LOITERING">Loitering</option>
            <option value="STATIONARY_OBJECT">Stationary Object</option>
            <option value="CROWD_DENSITY">Crowd Density</option>
            <option value="UNUSUAL_MOVEMENT">Unusual Movement</option>
          </select>
        </div>
      </div>

      {/* Events Table */}
      {isLoading ? (
        <div className="bg-[#111620] border border-[#1e2736] rounded-xl p-12 text-center text-xs text-[#8b96a8]">
          Loading security events...
        </div>
      ) : (
        <EventTable events={events} />
      )}
    </div>
  );
}
